### ISSUE TITLE
Uncaught TypeError: Cannot use 'in' operator to search for 'fields' in undefined

### ISSUE THREAD

**Issue by josejuanmartinez** [pueteam/datasource-plugin-solr#9]
Hola Sergio :)

   First, thank you for your work. I have been able to connect grafana to SOLR using your plugin. However, when I try to create any visualization or just to explore, it hangs and I can only see an error in the browser console:

**Uncaught TypeError: Cannot use 'in' operator to search for 'fields' in undefined**

I'm using SOLR 8 and grafana 7.0.5.

This is an example of documents in my SOLR index:

{
        "sentence":["—También voy a unos cursos de la Levinia Manfredini, la cosmetóloga."],
        "book_author":["Alberto Fuguet"],
        "book_title":["Mala onda"],
        "book_date":[2016],
        "book_lan":["es"],
        "book_var":["AR"],
        "timestamp":["2020-07-03T06:30:08Z"],
        "id":"c98b3f18-6478-48ab-bcfb-de0280f203c6",
        "_version_":1671316552046084096
},

Thanks!

**Comment by jschultze** [comment]
Hello,

I'm currently experiencing this error and was wondering if there was a solution to this problem?

**Comment by josejuanmartinez** [comment]
@jschultze I totally gave up on graphana + SOLR. It's totally broken.

**Comment by jschultze** [comment]
@josejuanmartinez  Not the answer I was hoping for ;) But thanks a lot for your quick reply! I'm currently trying to convert the XML I receive in response.data to JSON, but if that fails completely I'll move on.

Are you using some other grafana-like software in combination with Solr? Or could you recommend something?

**Comment by josejuanmartinez** [comment]
You can get JSON directly from SOLR. Use that (or convert from XML) and then upload it to Elasticsearch. That's the best way to go.

**Comment by jschultze** [comment]
Thanks, I'll have a look at that approach!
